### ISSUE TITLE
Links to "labs" in README.me are 404

### ISSUE THREAD

**Issue by alexdresko** [hackgvl/hackgreenville-com#143]
The README.md file has a few links to https://github.com/codeforgreenville which is 404. This may be related to [Add a "Labs" Page · Issue #138 · hackgvl/hackgreenville-com](https://github.com/hackgvl/hackgreenville-com/issues/138).

**Comment by allella** [comment]
I'd say we go ahead and fix the bad links now to point to [links](https://github.com/hackgvl) instead of waiting on the Labs page. 

Also, the Labs's can be updated to Labs' in the sentence
`HackGreenville Labs's Slack and visiting the #hackgreenville channel`

I've added a checklist at the top of https://github.com/hackgvl/hackgreenville-com/issues/138#issue-1768625592
which includes a reminder to modify the Readme to the /labs page at a later date.

**Comment by allella** [comment]
Actually, that sentence I mentioned is just goofy.

We should change it to something like

`[HackGreenville Slack](https://hackgreenville.com/join-slack) and visiting the #hg-labs channel`

**Comment by allella** [comment]
The https://hackgreenville.com/labs is now live, so we can link references to HG Labs to
https://hackgreenville.com/labs
as appropriate.
