### ISSUE TITLE
Events page search box

### ISSUE THREAD

**Issue by zach2825** [hackgvl/hackgreenville-com#170]
This might require converting the page to Livewire or something that will give search functionality. But it would be nice to be able to search for events on this page https://hackgreenville.com/events

We currently have a month filter, but this search could search across months to make finding events easier. 

Part of this work could be updated to the latest [Livewire three](https://livewire.laravel.com/) so we can use more template/ inline functionality.

**Comment by allella** [comment]
I'm curious what folks think about needing a search box.  It is possible to Ctrl + F or Cmd + F and search the content since it's already rendered, though, I'm sure not all users know that's a thing.

Is the idea this would search the title, or would it go further and search the event description or other fields that are part of the event model, but not necessarily shown on the view?

**Comment by allella** [comment]
The default view on my end is showing all months and I just noticed the month drop-down doesn't even do anything at the moment on my end, so perhaps this console error is breaking the month filter?

![image](https://github.com/hackgvl/hackgreenville-com/assets/1777776/eb46345f-e9b3-4c85-82be-74bc9cc5af8b)


https://hackgreenville.com/events

**Comment by bogdankharchenko** [comment]
@allella I submitted a PR to fix this, seems that when Vite was introduced, it broke this behavior.

#171

**Comment by bogdankharchenko** [comment]
I don't think we should introduce this feature.  It add unnecessary complexity.

**Comment by allella** [comment]
Thanks for the PR @bogdankharchenko 

Given how the UI works now with the fix, I think we could operate without a search feature, at least for now.

The default view shows all events, across all months, so a browser 'find' will work for any visible text.

I could see a search if we wanted to search hidden text for the events, or some tagging, but even that feature may return a lot of noise given the meetup event descriptions are sometimes truncated or have a lot of non-event related fluff.

We have a tagging system at the organizations API if we wanted to tag related organizations with specific keywords.  We've done that to group OpenWorks hosted events with a tag for displaying on our dashboard. Though, that's the tags approach for that use case is flawed because the orgs don't always host every event at OpenWorks. So, our dashboard has become more of a "what's happening here and with our partners".
