### ISSUE TITLE
Migrate Organization Management + Orgs API into Laravel

### ISSUE THREAD

**Issue by bogdankharchenko** [hackgvl/hackgreenville-com#187]
### Current workflow
We currently have a drupal admin which is used for managing an Organization List - which is then translated into an API end point `organizations.openupstate.org`.

While this solution is great, there are a few draw backs.
1. Currently we do not have a good way to actually write code for that repo. One of those things is having an ability for an organization to multiple event services.  While it is possible for this to be managed in drupal, it require a data migration and setting up additional controllers etc to handle this data
2. Drupal.

### Proposed Idea
1. We move the "Organizations" management to HackGreenville.com (this repo) - which is a laravel applications.
2. We offer an api for `Organizations` which will serve as the source of truth of managing these orgs.
3. Make any necessary migrations to the database to support various features such as organizations with multiple event service providers.
5. Create an Admin Crud system with https://filamentphp.com/ (fairly easy task, Laravel Admin Tool, amazing to work with)

### Final thoughts
This may seem like a lot of work, but its will take more work to many any changes to the drupal site than it will to migrate this into Laravel

#186  Organization API is basically complete.

**Comment by allella** [comment]
I'm not fighting to keep the Drupal implementation, but I'll add historical context and other notes.  It does some things out of the box, or with clicks, that may need to be factored into the scope of rolling our own replacement.

@bogdankharchenko and @ThorntonMatthewD I'll add accounts for you so you can see some of what it does for authenticated users to get ideas for what might need to be replaced or what's not needed.

The Drupal code can certainly be added to a Git repo, but I just never bothered because most of the contributors were just helping enter data in Drupal and didn't need to run a dev copy.

Also, since there's a database, having a repo of Drupal alone doesn't make it where people can just setup a new instance and start doing things.  It is possible to export UI defined field definitions, views, and configuration to code, but this site was created shortly after Drupal 8 was released and I wasn't too familiar with the best way to do that. Plus, it was a problem nobody had, so I focused on just getting things to work and giving people logins to help with the data.

To Bogdan's point, not many people know Drupal, so hardly anybody has asked how to contribute. To Drupal's credit, there's been little reason for anybody to need to write code for it, since you can do so much by clicking buttons. I've dealt with writing the little bit of custom code that's been needed for the nearly 8 years it's been running.

I'm sure Laravel has packages for the GUI, auth side and other bells and whistles, but Drupal comes with a lot out of the box, so it may be a decent task to replicate even the minimum scope.

Keeping Drupal up to date takes work to patch security and deal with module an core upgrades. Minor versions typically aren't an issue, but I did recently start moving to Drupal 10 and there was an unexpected breaking change that required rolling back to a snapshot to fix.  Drupal has gotten much better about not having major version upgrades being a big deal ever since they adopted the Symfony core in Drupal 8, but it's still work to patch security and do minor and major upgrades. Though, even with Laravel someone has to do similar work when there are major versions, so it's work by someone regardless of the tool.

The other main thing is we have the map layers setup in Drupal too.  While we could continue to host just the map layers there, I'd rather not maintain the site just for that purpose.  Some of the map layer stuff could possibly be static pages and moved under a GitHub pages. Other stuff is dynamic and would require more than GitHub pages.

  Since the demo map is in Vue, it could make sense to rebuild some of the other map pages, like
- Map list https://data.openupstate.org/map-layers
- Detail pags like https://data.openupstate.org/map/co-working-spaces
in the same static app and host it all on GitHub pages under a subdomain.

Though, there are some dynamic pieces we'd have to host somewhere too, like
- GeoJSON script to pull data from Google Spreadsheets in real-time (or near real-time). This is currently written in PHP and uses a slug value in the request URL to map to a spreadsheet CSV link in the Drupal content (database).
- Scripts to pull copies of syndicated data from Greenville County (currently these are shell scripts)

So, we could move the map stuff to Vue, or PHP, or a combination of both.  

Drupal historically hasn't been a bottleneck on progress since non-coders can log in and click buttons to edit stuff, and since there haven't been many pressing tasks until Carolina Code School threw a new wrench in things by using both Eventbrite and Meetup to host events. https://github.com/hackgvl/events-api/issues/70

https://github.com/hackgvl/events-api/issues/70 on the existing orgs side would likely be a matter of clicking buttons to make a compound field to allow for 1 or more (event_service + events_api_key) for any org and then some rework of the Events API to deal with the same change.

Other things that Drupal does out of the box, or with clicking on a contributed module UI, that we'd probably not want to lose.

- We could very well put the orgs data into a raw JSON file and do away with any forms and UI. I suspect we might prefer the orgs data in an actual database to allow for better filtering and caching and such. So, we probably don't want to do away with the CMS components of the adding and editing orgs by an authenticated user.
- A taxonomy interface to allow folks to tag orgs with specific tags, which can be filtered in the orgs API.  Admittedly, I'm the main user of that feature, with tagging OpenWorks' events for our dashboard, but it is something we'd want to maintain in some form.
- Meta tag description fields for pages for SEO
- Path redirects for SEO, like when we've changed URLs or someone is sending traffic to a typo URL and we want to redirect it to the correct place.
- Contact forms and ReCaptcha and honey pot CAPTHCA protection on forms - we could probably use the HackGreenville forms as an alternative, so I'm not too worried if these went away. Plus, hardly anybody uses them but maybe once a year or less.
- We've never found a need, but all of the content "nodes" in Drupal also have JSON views and REST [endpoints for CRUD on the content](https://github.com/hackgvl/OpenData/blob/master/ORGANIZATIONS_API.md#example-of-creating-a-new-organization). I don't think this is something we'd need to worry about, but it is baked in to the CMS that nodes aren't just HTML pages. 
- We could probably move the data.openupstate.org content into GitHub documentation, or a Wiki, but that's another CMS element that's part of the current Drupal context.
- As mentioned above, things related to the map layers

**Comment by allella** [comment]
Add a reminder that the version of the orgs API in the Laravel stack does not implement fields all of the fields from [the original orgs API](https://data.openupstate.org/rest/organizations?_format=json).
 
[field_year_inactive, field_regular_start_time, field_regular_day_of_the_month](https://github.com/hackgvl/hackgreenville-com/pull/186/files#r1394408371
) 

and in the tests app-modules/api/tests/Feature/EventApiV0Test.php
