### ISSUE TITLE
`/style-guide` Raises HTTP 500 Error

### ISSUE THREAD

**Issue by ThorntonMatthewD** [hackgvl/hackgreenville-com#190]
https://hackgreenville.com/style-guide raises an [HTTP 500](https://http.cat/500) error.

The error:
> App\Http\Controllers\StyleController::styleGuide does not exist.

Perhaps this route can be removed?

**Comment by allella** [comment]
The URL at https://hackgreenville.com/styles is working. Where are we linking to /style-guide?

**Comment by allella** [comment]
There's a "Styles" link in the footer and is what's indexed in the search engines, so this doesn't look like a recent change

![image](https://github.com/hackgvl/hackgreenville-com/assets/1777776/822e98c0-02b6-46b2-a926-1b146b3e7aa8)

Maybe do a git blame and see who added it and how long ago, but it seems like it's never been used.

**Comment by ThorntonMatthewD** [comment]
> The URL at https://hackgreenville.com/styles is working. Where are we linking to /style-guide?

I came across it [here](https://github.com/hackgvl/hackgreenville-com/blob/6d4ecd0da84f97040b54b04a9da8f0ef8711b0df/routes/web.php#L31) while debugging a possible routing issue elsewhere. I don't believe it is linked to anywhere.

**Comment by allella** [comment]
Looks like Zach added the /style-guide route in #137.  I don't think we need it since /style has been active for years, but checking with @zach2825 if there was a reason for the /style-guide route since it's returning a 500 error since there's no corresponding _StyleController@styleGuide_

![image](https://github.com/hackgvl/hackgreenville-com/assets/1777776/149857db-4faa-4f11-b2d6-5e6359f43216)

**Comment by bogdankharchenko** [comment]
PR a deletion of that route.
