### ISSUE TITLE
Allow members to post that they have a job

### ISSUE THREAD

**Issue by zach2825** [hackgvl/hackgreenville-com#48]
This might be a way to request help on a project or something. could be some sort of simple message board.

**Comment by allella** [comment]
I feel this is already something offered by the Slack.  If anything with jobs and things like that I figure we could syndicate some of the conversations or posts in Slack so the pages are dynamic, but I'm not even sure if that's the best idea because then the content in Slack requires more moderation.

What were you thinking?

**Comment by zach2825** [comment]
Im just trying to come up with things that show that were active in the community

**Comment by allella** [comment]
That's good. I'm just trying to make sure there's little or no manual work or human dependency.  A huge part of what makes the events API work is that we're reusing data that organizers are forced to create.  If we asked organizers to update a calendar every month it would have failed in the first month.

Doing something like highlighting curated content from Slack and having it automatically show on the webpage would be cool. I'm not sure if that's possible to get info out of Slack, but if it were I wonder if we could show things that get over a certain number of thumbs up. Or, if a post is pinned, or something like that where the post is popular or elevated by a moderator, so it also magically shows on the HG site.

Of course, if this is possible we'd want to avoid people being able to game it to do nasty things or promote themselves by cheating the system.

**Comment by zach2825** [comment]
That's what I was thinking. To create slack integration. Maybe you type something like  "/hg-post job JOBTITLE JOBDESCCRIPTION EXPIRE_DATE" then it asks for approval from an admin in slack then it posts to the page.

**Comment by allella** [comment]
I'll try to get the HG admins to chime in if/when they join GitHub.

Also, as far as features, we did a [survey using this form](https://forms.gle/8MmJHeJrsYsVGprR7) and the results were re-shared today in the #hackgreenville Code For Greenville Slack.

**Comment by bogdankharchenko** [comment]
We should backlog this - and get rid of this issue.  As this is not an issue.

**Comment by allella** [comment]
@bogdankharchenko  regarding https://github.com/hackgvl/hackgreenville-com/issues/361#issuecomment-2271308777

I'm assuming adding to the project would just be a draft item, but these doesn't give much ability to have a conversation.

What I've seen done before by freeCodeCamp is to close the issues, but [leave a specific tag / label of "Roadmap" for future reference](https://github.com/freeCodeCamp/chapter/issues?q=is%3Aopen+is%3Aissue+label%3ARoadmap).  If we did that we could create a new project view that highlights those closed and tagged with Roadmap as a way to retain all of the capabilities we currently have, but not have ideas clogging up the issues queue.

Is that a reasonable approach?

![image](https://github.com/user-attachments/assets/cd17d1eb-0816-43fb-ab65-79be6475304f)

**Comment by bogdankharchenko** [comment]
I understand where you are coming from - I definitely wouldn't want to stiffen conversation... but this ticket has been here since 2020... At some point we should either delete this issue until it resurfaces or commit to working on it soon. I just think its taking up real estate in the issues tab as "need to work on this issue"

We could introduce "discussions" in the this repo - or just a project specific for this repo.  Or just delete this all together. 

Same goes for a lot of the old issues -- are they really important? -- if not we should just close them/backlog them

**Comment by allella** [comment]
I think you missed where I said "Close" the issue. 

Closing the issue and labeling it solves your concerns and mine.

**Comment by allella** [comment]
@bogdankharchenko here's what I had in mind.  

I closed this issue and tagged it with "Suggestion".

There is a new project with an auto-add workflow to add _is:issue is:closed label:"suggestion"_ 

and we can have multiple views on that project, like the [first view to show only suggested ideas for HackGreenville.com](https://github.com/orgs/hackgvl/projects/7/views/1)
